[package]
name = "epoll_reactor"
version = "0.1.0"
authors = ["sfortas <sebastien.fortas@gmail.com>"]
edition = "2018"
autoexamples = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.98"
